"""
Pre-built industry packs for Reverse ATS.
Each pack contains ~15-30 companies with their ATS configuration.
Users can install packs from Admin → Company Manager → Industry Packs.
"""

PACKS = {
    "tech_fintech": {
        "name": "Tech & Fintech (Default)",
        "description": "54 companies pre-installed: FAANG, fintech, AI, quant firms. Already active.",
        "icon": "laptop",
        "companies": [],
    },
    "healthcare": {
        "name": "Healthcare & Life Sciences",
        "description": "Health systems, biotech, pharma, health IT, digital health",
        "icon": "heart",
        "companies": [
            {"name": "Epic Systems", "ats": "custom", "slug": "epic", "careers_url": "https://careers.epic.com/"},
            {"name": "Cerner (Oracle Health)", "ats": "custom", "slug": "oracle-health", "careers_url": "https://www.oracle.com/careers/"},
            {"name": "UnitedHealth Group", "ats": "custom", "slug": "uhg", "careers_url": "https://careers.unitedhealthgroup.com/"},
            {"name": "CVS Health", "ats": "custom", "slug": "cvs", "careers_url": "https://jobs.cvshealth.com/"},
            {"name": "Elevance Health", "ats": "custom", "slug": "elevance", "careers_url": "https://careers.elevancehealth.com/"},
            {"name": "HCA Healthcare", "ats": "custom", "slug": "hca", "careers_url": "https://careers.hcahealthcare.com/"},
            {"name": "Humana", "ats": "custom", "slug": "humana", "careers_url": "https://careers.humana.com/"},
            {"name": "Veeva Systems", "ats": "greenhouse", "slug": "veeva"},
            {"name": "Flatiron Health", "ats": "greenhouse", "slug": "flatironhealth"},
            {"name": "Tempus", "ats": "greenhouse", "slug": "tempus"},
            {"name": "Color Health", "ats": "greenhouse", "slug": "colorgenomics"},
            {"name": "Ro", "ats": "greenhouse", "slug": "ro"},
            {"name": "Hims & Hers", "ats": "greenhouse", "slug": "himshers"},
            {"name": "GoodRx", "ats": "greenhouse", "slug": "goodrx"},
            {"name": "Zocdoc", "ats": "greenhouse", "slug": "zocdoc"},
            {"name": "Teladoc", "ats": "custom", "slug": "teladoc", "careers_url": "https://www.teladochealth.com/careers/"},
            {"name": "Aledade", "ats": "greenhouse", "slug": "aledade"},
            {"name": "Included Health", "ats": "greenhouse", "slug": "includedhealth"},
            {"name": "Sword Health", "ats": "greenhouse", "slug": "swordhealth"},
            {"name": "Komodo Health", "ats": "greenhouse", "slug": "komodohealth"},
            {"name": "Verily", "ats": "greenhouse", "slug": "verily"},
            {"name": "Illumina", "ats": "custom", "slug": "illumina", "careers_url": "https://www.illumina.com/company/careers.html"},
            {"name": "Moderna", "ats": "custom", "slug": "moderna", "careers_url": "https://www.modernatx.com/careers"},
            {"name": "Pfizer", "ats": "custom", "slug": "pfizer", "careers_url": "https://careers.pfizer.com/"},
            {"name": "Johnson & Johnson", "ats": "custom", "slug": "jnj", "careers_url": "https://jobs.jnj.com/"},
            {"name": "Abbott", "ats": "custom", "slug": "abbott", "careers_url": "https://www.jobs.abbott/"},
            {"name": "Medtronic", "ats": "custom", "slug": "medtronic", "careers_url": "https://jobs.medtronic.com/"},
        ],
    },
    "consulting_professional": {
        "name": "Consulting & Professional Services",
        "description": "Big 4, management consulting, IT consulting, staffing",
        "icon": "briefcase",
        "companies": [
            {"name": "McKinsey", "ats": "custom", "slug": "mckinsey", "careers_url": "https://www.mckinsey.com/careers"},
            {"name": "BCG", "ats": "custom", "slug": "bcg", "careers_url": "https://careers.bcg.com/"},
            {"name": "Bain & Company", "ats": "custom", "slug": "bain", "careers_url": "https://www.bain.com/careers/"},
            {"name": "Deloitte", "ats": "custom", "slug": "deloitte", "careers_url": "https://www.deloitte.com/us/en/careers.html"},
            {"name": "PwC", "ats": "custom", "slug": "pwc", "careers_url": "https://www.pwc.com/us/en/careers.html"},
            {"name": "EY", "ats": "custom", "slug": "ey", "careers_url": "https://www.ey.com/en_us/careers"},
            {"name": "KPMG", "ats": "custom", "slug": "kpmg", "careers_url": "https://kpmg.com/us/en/careers.html"},
            {"name": "Accenture", "ats": "custom", "slug": "accenture", "careers_url": "https://www.accenture.com/us-en/careers"},
            {"name": "Booz Allen Hamilton", "ats": "custom", "slug": "boozallen", "careers_url": "https://careers.boozallen.com/"},
            {"name": "Slalom", "ats": "greenhouse", "slug": "slalom"},
            {"name": "Thoughtworks", "ats": "greenhouse", "slug": "thoughtworks"},
            {"name": "Cognizant", "ats": "custom", "slug": "cognizant", "careers_url": "https://careers.cognizant.com/"},
            {"name": "Infosys", "ats": "custom", "slug": "infosys", "careers_url": "https://www.infosys.com/careers/"},
            {"name": "Wipro", "ats": "custom", "slug": "wipro", "careers_url": "https://careers.wipro.com/"},
            {"name": "Capgemini", "ats": "custom", "slug": "capgemini", "careers_url": "https://www.capgemini.com/careers/"},
            {"name": "CGI", "ats": "custom", "slug": "cgi", "careers_url": "https://www.cgi.com/en/careers"},
            {"name": "Gartner", "ats": "custom", "slug": "gartner", "careers_url": "https://jobs.gartner.com/"},
            {"name": "Forrester", "ats": "greenhouse", "slug": "forrester"},
            {"name": "West Monroe", "ats": "greenhouse", "slug": "westmonroe"},
            {"name": "Point72", "ats": "greenhouse", "slug": "point72"},
        ],
    },
    "ecommerce_retail": {
        "name": "E-Commerce & Retail",
        "description": "Online marketplaces, retail tech, DTC brands, logistics",
        "icon": "shopping-cart",
        "companies": [
            {"name": "Shopify", "ats": "greenhouse", "slug": "shopify"},
            {"name": "Instacart", "ats": "greenhouse", "slug": "instacart"},
            {"name": "DoorDash", "ats": "greenhouse", "slug": "doordash"},
            {"name": "Uber", "ats": "greenhouse", "slug": "uber"},
            {"name": "Lyft", "ats": "greenhouse", "slug": "lyft"},
            {"name": "Airbnb", "ats": "greenhouse", "slug": "airbnb"},
            {"name": "Etsy", "ats": "greenhouse", "slug": "etsy"},
            {"name": "Wayfair", "ats": "greenhouse", "slug": "wayfair"},
            {"name": "Chewy", "ats": "greenhouse", "slug": "chewy"},
            {"name": "Target", "ats": "custom", "slug": "target", "careers_url": "https://corporate.target.com/careers"},
            {"name": "Walmart", "ats": "custom", "slug": "walmart", "careers_url": "https://careers.walmart.com/technology"},
            {"name": "Costco", "ats": "custom", "slug": "costco", "careers_url": "https://www.costco.com/jobs.html"},
            {"name": "Nike", "ats": "custom", "slug": "nike", "careers_url": "https://jobs.nike.com/"},
            {"name": "Stitch Fix", "ats": "greenhouse", "slug": "stitchfix"},
            {"name": "ThredUp", "ats": "greenhouse", "slug": "thredup"},
            {"name": "Faire", "ats": "greenhouse", "slug": "faire"},
            {"name": "Flexport", "ats": "greenhouse", "slug": "flexport"},
            {"name": "Bolt", "ats": "greenhouse", "slug": "bolt"},
            {"name": "Fanatics", "ats": "greenhouse", "slug": "fanatics"},
            {"name": "Poshmark", "ats": "custom", "slug": "poshmark", "careers_url": "https://poshmark.com/careers"},
            {"name": "Warby Parker", "ats": "greenhouse", "slug": "warbyparker"},
            {"name": "Peloton", "ats": "greenhouse", "slug": "peloton"},
            {"name": "Gopuff", "ats": "greenhouse", "slug": "gopuff"},
        ],
    },
    "media_entertainment": {
        "name": "Media & Entertainment",
        "description": "Streaming, gaming, social media, content platforms, news",
        "icon": "film",
        "companies": [
            {"name": "Spotify", "ats": "greenhouse", "slug": "spotify"},
            {"name": "Disney", "ats": "custom", "slug": "disney", "careers_url": "https://jobs.disneycareers.com/"},
            {"name": "Warner Bros Discovery", "ats": "custom", "slug": "wbd", "careers_url": "https://careers.wbd.com/"},
            {"name": "NBCUniversal", "ats": "custom", "slug": "nbcuniversal", "careers_url": "https://www.nbcunicareers.com/"},
            {"name": "Sony", "ats": "custom", "slug": "sony", "careers_url": "https://www.sonyjobs.com/"},
            {"name": "Roblox", "ats": "greenhouse", "slug": "roblox"},
            {"name": "Unity", "ats": "greenhouse", "slug": "unity3d"},
            {"name": "Epic Games", "ats": "greenhouse", "slug": "epicgames"},
            {"name": "Riot Games", "ats": "greenhouse", "slug": "riotgames"},
            {"name": "EA", "ats": "custom", "slug": "ea", "careers_url": "https://www.ea.com/careers"},
            {"name": "Reddit", "ats": "greenhouse", "slug": "reddit"},
            {"name": "Pinterest", "ats": "greenhouse", "slug": "pinterest"},
            {"name": "Snap", "ats": "greenhouse", "slug": "snap"},
            {"name": "Discord", "ats": "greenhouse", "slug": "discord"},
            {"name": "Twitch", "ats": "greenhouse", "slug": "twitch"},
            {"name": "The New York Times", "ats": "greenhouse", "slug": "thenewyorktimes"},
            {"name": "Bloomberg", "ats": "greenhouse", "slug": "bloomberg"},
            {"name": "Vox Media", "ats": "greenhouse", "slug": "voxmedia"},
            {"name": "Substack", "ats": "greenhouse", "slug": "substack"},
            {"name": "Audible", "ats": "greenhouse", "slug": "audible"},
        ],
    },
    "enterprise_saas": {
        "name": "Enterprise SaaS & Cloud",
        "description": "B2B software, cloud infrastructure, dev tools, security",
        "icon": "cloud",
        "companies": [
            {"name": "Salesforce", "ats": "custom", "slug": "salesforce", "careers_url": "https://careers.salesforce.com/"},
            {"name": "ServiceNow", "ats": "custom", "slug": "servicenow", "careers_url": "https://careers.servicenow.com/"},
            {"name": "Snowflake", "ats": "greenhouse", "slug": "snowflake"},
            {"name": "Confluent", "ats": "greenhouse", "slug": "confluent"},
            {"name": "MongoDB", "ats": "greenhouse", "slug": "mongodb"},
            {"name": "Elastic", "ats": "greenhouse", "slug": "elastic"},
            {"name": "HashiCorp", "ats": "greenhouse", "slug": "hashicorp"},
            {"name": "Cloudflare", "ats": "greenhouse", "slug": "cloudflare"},
            {"name": "Twilio", "ats": "greenhouse", "slug": "twilio"},
            {"name": "Okta", "ats": "greenhouse", "slug": "okta"},
            {"name": "CrowdStrike", "ats": "greenhouse", "slug": "crowdstrike"},
            {"name": "Palo Alto Networks", "ats": "custom", "slug": "paloalto", "careers_url": "https://jobs.paloaltonetworks.com/"},
            {"name": "Zscaler", "ats": "greenhouse", "slug": "zscaler"},
            {"name": "Splunk", "ats": "custom", "slug": "splunk", "careers_url": "https://www.splunk.com/en_us/careers.html"},
            {"name": "New Relic", "ats": "greenhouse", "slug": "newrelic"},
            {"name": "PagerDuty", "ats": "greenhouse", "slug": "pagerduty"},
            {"name": "Atlassian", "ats": "greenhouse", "slug": "atlassian"},
            {"name": "Asana", "ats": "greenhouse", "slug": "asana"},
            {"name": "monday.com", "ats": "greenhouse", "slug": "mondaycom"},
            {"name": "Airtable", "ats": "greenhouse", "slug": "airtable"},
            {"name": "Canva", "ats": "greenhouse", "slug": "canva"},
            {"name": "Miro", "ats": "greenhouse", "slug": "miro"},
            {"name": "Linear", "ats": "ashby", "slug": "linear"},
            {"name": "1Password", "ats": "greenhouse", "slug": "1password"},
            {"name": "GitLab", "ats": "greenhouse", "slug": "gitlab"},
            {"name": "JFrog", "ats": "greenhouse", "slug": "jfrog"},
            {"name": "LaunchDarkly", "ats": "greenhouse", "slug": "launchdarkly"},
            {"name": "Postman", "ats": "greenhouse", "slug": "postman"},
            {"name": "Kong", "ats": "greenhouse", "slug": "kong"},
            {"name": "Grafana Labs", "ats": "greenhouse", "slug": "grafanalabs"},
        ],
    },
    "education": {
        "name": "Education & EdTech",
        "description": "Online learning, K-12, higher ed tech, ed platforms",
        "icon": "book",
        "companies": [
            {"name": "Coursera", "ats": "greenhouse", "slug": "coursera"},
            {"name": "Duolingo", "ats": "greenhouse", "slug": "duolingo"},
            {"name": "Khan Academy", "ats": "greenhouse", "slug": "khanacademy"},
            {"name": "Chegg", "ats": "greenhouse", "slug": "chegg"},
            {"name": "Instructure", "ats": "greenhouse", "slug": "instructure"},
            {"name": "2U", "ats": "greenhouse", "slug": "2u"},
            {"name": "Cengage", "ats": "custom", "slug": "cengage", "careers_url": "https://www.cengage.com/careers/"},
            {"name": "McGraw Hill", "ats": "custom", "slug": "mcgrawhill", "careers_url": "https://careers.mheducation.com/"},
            {"name": "Pearson", "ats": "custom", "slug": "pearson", "careers_url": "https://www.pearson.com/careers.html"},
            {"name": "Skillsoft", "ats": "greenhouse", "slug": "skillsoft"},
            {"name": "Brainly", "ats": "greenhouse", "slug": "brainly"},
            {"name": "Handshake", "ats": "greenhouse", "slug": "handshake"},
            {"name": "ClassDojo", "ats": "greenhouse", "slug": "classdojo"},
            {"name": "Quizlet", "ats": "greenhouse", "slug": "quizlet"},
            {"name": "Outschool", "ats": "greenhouse", "slug": "outschool"},
        ],
    },
    "government_defense": {
        "name": "Government & Defense Tech",
        "description": "GovTech, defense contractors, civic tech, federal IT",
        "icon": "shield",
        "companies": [
            {"name": "Palantir", "ats": "lever", "slug": "palantir"},
            {"name": "Anduril", "ats": "greenhouse", "slug": "anduril"},
            {"name": "Shield AI", "ats": "greenhouse", "slug": "shieldai"},
            {"name": "SpaceX", "ats": "greenhouse", "slug": "spacex"},
            {"name": "Lockheed Martin", "ats": "custom", "slug": "lockheed", "careers_url": "https://www.lockheedmartinjobs.com/"},
            {"name": "Raytheon", "ats": "custom", "slug": "raytheon", "careers_url": "https://www.rtx.com/careers"},
            {"name": "Northrop Grumman", "ats": "custom", "slug": "northrop", "careers_url": "https://www.northropgrumman.com/careers"},
            {"name": "General Dynamics", "ats": "custom", "slug": "gd", "careers_url": "https://www.gd.com/careers"},
            {"name": "BAE Systems", "ats": "custom", "slug": "bae", "careers_url": "https://jobs.baesystems.com/"},
            {"name": "L3Harris", "ats": "custom", "slug": "l3harris", "careers_url": "https://careers.l3harris.com/"},
            {"name": "SAIC", "ats": "custom", "slug": "saic", "careers_url": "https://jobs.saic.com/"},
            {"name": "Leidos", "ats": "custom", "slug": "leidos", "careers_url": "https://careers.leidos.com/"},
            {"name": "Maxar", "ats": "greenhouse", "slug": "maxar"},
            {"name": "Rebellion Defense", "ats": "greenhouse", "slug": "rebelliondefense"},
            {"name": "Govini", "ats": "greenhouse", "slug": "govini"},
            {"name": "Primer AI", "ats": "greenhouse", "slug": "primer"},
            {"name": "Second Front Systems", "ats": "greenhouse", "slug": "secondfrontsystems"},
            {"name": "Vannevar Labs", "ats": "greenhouse", "slug": "vannevarlabs"},
        ],
    },
    "climate_energy": {
        "name": "Climate & Clean Energy",
        "description": "Renewables, EVs, carbon tech, energy storage, sustainability",
        "icon": "leaf",
        "companies": [
            {"name": "Tesla", "ats": "custom", "slug": "tesla", "careers_url": "https://www.tesla.com/careers"},
            {"name": "Rivian", "ats": "greenhouse", "slug": "rivian"},
            {"name": "Lucid Motors", "ats": "greenhouse", "slug": "lucidmotors"},
            {"name": "ChargePoint", "ats": "greenhouse", "slug": "chargepoint"},
            {"name": "Bloom Energy", "ats": "greenhouse", "slug": "bloomenergy"},
            {"name": "Enphase Energy", "ats": "greenhouse", "slug": "enphaseenergy"},
            {"name": "SunPower", "ats": "custom", "slug": "sunpower", "careers_url": "https://us.sunpower.com/careers"},
            {"name": "Arcadia", "ats": "greenhouse", "slug": "arcadia"},
            {"name": "Span.IO", "ats": "greenhouse", "slug": "span"},
            {"name": "Watershed", "ats": "greenhouse", "slug": "watershed"},
            {"name": "Pachama", "ats": "greenhouse", "slug": "pachama"},
            {"name": "Redwood Materials", "ats": "greenhouse", "slug": "redwoodmaterials"},
            {"name": "Form Energy", "ats": "greenhouse", "slug": "formenergy"},
            {"name": "QuantumScape", "ats": "greenhouse", "slug": "quantumscape"},
        ],
    },
}

# Auto-calculate counts and set default category for each company
for pack_id, pack in PACKS.items():
    pack["count"] = len(pack.get("companies", []))
    for company in pack.get("companies", []):
        company.setdefault("category", pack_id)


def get_available_packs() -> list[dict]:
    """Return pack metadata (without full company lists) for the UI."""
    return [
        {
            "id": pack_id,
            "name": pack["name"],
            "description": pack["description"],
            "count": pack["count"],
        }
        for pack_id, pack in PACKS.items()
    ]


def get_pack_companies(pack_id: str) -> list[dict]:
    """Return the full company list for a specific pack."""
    pack = PACKS.get(pack_id)
    if not pack:
        return []
    return pack.get("companies", [])
